import type { Prefeitura, Usuario } from './types'

export const PREFEITURAS_SEED: Prefeitura[] = [
  {
    id: 'tl-ms',
    nome: 'Três Lagoas',
    uf: 'MS',
    contrato: {
      numero: '045/2025',
      processo: 'PE 012/2025',
      modalidade: 'pregao_eletronico',
      dataAssinatura: '2025-02-10',
      vigenciaInicio: '2025-03-01',
      vigenciaFim: '2028-02-28',
      objeto:
        'Prestação de serviços de gestão integrada da frota municipal: cadastro de veículos e equipamentos, checklists preventivos, ordens de serviço, indicadores e relatórios gerenciais.',
      valorMensal: 'R$ 18.500,00',
      valorTotal: 'R$ 666.000,00',
      indiceReajuste: 'IPCA',
      periodicidadeFaturamento: 'mensal',
      slaRespostaHoras: '24',
      responsavelContratante: 'João da Silva',
      cargoContratante: 'Secretário Municipal de Administração',
      emailContratante: 'frota@treslagoas.ms.gov.br',
      telefoneContratante: '(67) 3521-7000',
      observacoes:
        'Renovação automática por igual período, salvo manifestação contrária com antecedência mínima de 90 dias.',
      status: 'ativo',
    },
  },
  {
    id: 'curitiba-pr',
    nome: 'Curitiba',
    uf: 'PR',
    contrato: {
      numero: '128/2024',
      processo: 'DL 008/2024',
      modalidade: 'pregao_eletronico',
      dataAssinatura: '2024-08-15',
      vigenciaInicio: '2024-09-01',
      vigenciaFim: '2027-08-31',
      objeto:
        'Gestão da manutenção da frota pesada e leve do município, incluindo painel de indicadores e integração com oficinas credenciadas.',
      valorMensal: 'R$ 42.000,00',
      valorTotal: 'R$ 1.512.000,00',
      indiceReajuste: 'IPCA',
      periodicidadeFaturamento: 'mensal',
      slaRespostaHoras: '48',
      responsavelContratante: 'Ana Pereira Costa',
      cargoContratante: 'Diretora de Frota',
      emailContratante: 'frota@curitiba.pr.gov.br',
      telefoneContratante: '(41) 3350-9000',
      observacoes: 'Multas e penalidades conforme cláusula 12 do edital.',
      status: 'ativo',
    },
  },
  {
    id: 'bh-mg',
    nome: 'Belo Horizonte',
    uf: 'MG',
    contrato: {
      numero: '901/2024',
      processo: 'CP 44/2024',
      modalidade: 'credenciamento',
      dataAssinatura: '2024-11-20',
      vigenciaInicio: '2025-01-01',
      vigenciaFim: '2029-12-31',
      objeto:
        'Plataforma de gestão de frota, telemetria básica, OS de manutenção corretiva e preventiva e compliance documental.',
      valorMensal: 'R$ 98.000,00',
      valorTotal: 'R$ 5.880.000,00',
      indiceReajuste: 'IPCA + 0,5%',
      periodicidadeFaturamento: 'mensal',
      slaRespostaHoras: '12',
      responsavelContratante: 'Carlos Mendes',
      cargoContratante: 'Coordenador de Patrimônio Móvel',
      emailContratante: 'frota@prefeitura.pbh.gov.br',
      telefoneContratante: '(31) 3277-7000',
      observacoes: 'Aditivos mediante termo específico.',
      status: 'ativo',
    },
  },
]

export const DEFAULT_USERS: Usuario[] = [
  {
    nome: 'Administrador Três Lagoas',
    usuario: 'admin',
    senha: 'admin123',
    perfil: 'admin',
    prefeituraId: 'tl-ms',
    vinculo: 'prefeitura',
  },
  {
    nome: 'Gestor Curitiba',
    usuario: 'gestor',
    senha: 'gestor123',
    perfil: 'gestor',
    prefeituraId: 'curitiba-pr',
    vinculo: 'prefeitura',
  },
  {
    nome: 'Administrador BH',
    usuario: 'admin.bh',
    senha: 'bh123456',
    perfil: 'admin',
    prefeituraId: 'bh-mg',
    vinculo: 'prefeitura',
  },
  {
    nome: 'Frentista / operador posto (demo)',
    usuario: 'posto.tl',
    senha: 'posto123',
    perfil: 'gestor',
    prefeituraId: 'tl-ms',
    vinculo: 'posto',
    postoId: 'posto-tl-ms-001',
  },
]
